<?php

/**
 * @file
 * Primary module hooks for Maintenance Node module.
 */

use Drupal\node\Entity\Node;

/**
 * Implements hook_preprocess_template()
 * Load node from config to show in maintenance mode.
 */
function maintenance_node_preprocess_maintenance_page(&$variables) {

  $maintenance_node_id = \Drupal::config('maintenance.node')->get('maintenance_node');
  if (!$maintenance_node_id) {
    return;
  }

  $node = \Drupal::service('entity_type.manager')->getStorage('node')->load($maintenance_node_id);
  if (!($node instanceof Node)) {
    return;
  }

  $builder = \Drupal::entityTypeManager()->getViewBuilder('node');
  $build = $builder->view($node, 'master');
  $variables['maintenance_node'] = \Drupal::service('renderer')->render($build);
}

/**
 * Implements hook_theme_registry_alter
 */
function maintenance_node_theme_registry_alter(&$theme_registry) {
  $theme_registry['maintenance_page']['path'] = \Drupal::service('extension.list.module')->getPath('maintenance_node') . '/templates';
}
